---
- name: Clear current state from backend
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Delete current state
      ansible.builtin.uri:
        url: "{{ lookup('env', 'TF_HTTP_ADDRESS') }}"
        method: DELETE
        headers:
          Private-Token: "{{ lookup('env', 'secret_GLOBAL_API_TOKEN') }}"

