---
- name: Create VM using data from pipeline environment
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Plan VM deploy using terraform
      ansible.builtin.shell: |
        terraform -chdir=$CI_PROJECT_DIR/core/terraform apply -var-file="$CI_PROJECT_DIR/environments/$CI_ENVIRONMENT_NAME.tfvars" -auto-approve