---
- name: Clear infrastructure resources
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Destroy deploy using terraform
      ansible.builtin.shell: |
        terraform -chdir=$CI_PROJECT_DIR/core/terraform destroy -var-file="$CI_PROJECT_DIR/environments/$CI_ENVIRONMENT_NAME.tfvars" --auto-approve
