---
- name: Prepares project for infrastructure deployment
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Initialize terraform project
      ansible.builtin.shell: |
        terraform -chdir=$CI_PROJECT_DIR/core/terraform init
    
    - name: Validate terraform configuration
      ansible.builtin.shell: |
        terraform -chdir=$CI_PROJECT_DIR/core/terraform validate
