stages:
  - production

include:
  - local: '/core/pipeline/include/setup.gitlab-ci.yml'
  - local: '/core/pipeline/include/base.gitlab-ci.yml'
  - local: '/core/pipeline/include/infraestructure.gitlab-ci.yml'
  - local: '/core/pipeline/include/service.gitlab-ci.yml'

.production:
  extends: .base
  stage: production
  environment:
    name: production
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: manual

.production-deploy:
  extends: .production
  before_script:
    - !reference [.setup, before_script]
  script:
    - !reference [.infraestructure_init, script]
    - !reference [.infraestructure_create, script]
    - !reference [.service_deploy, script]

.production-redeploy:
  extends: .production
  before_script:
    - !reference [.setup, before_script]
  script:
    - !reference [.infraestructure_init, script]
    - !reference [.infraestructure_delete, script]
    - !reference [.infraestructure_create, script]
    - !reference [.service_deploy, script]
  allow_failure: true

.production-safe-redeploy:
  extends: .production
  before_script:
    - !reference [.setup, before_script]
  script:
    - !reference [.infraestructure_init, script]
    - !reference [.infraestructure_archive, script]
    - !reference [.infraestructure_clear_state, script]
    - !reference [.infraestructure_init, script]
    - !reference [.infraestructure_create, script]
    - !reference [.service_deploy, script]

.production-inventory:
  extends: .production
  artifacts:
    untracked: false
    paths:
      - $CI_PROJECT_DIR/outputs_$CI_ENVIRONMENT_NAME.json
      - $CI_PROJECT_DIR/inventory_$CI_ENVIRONMENT_NAME.txt
    when: on_success
    expire_in: "30 days"
  before_script:
    - !reference [.setup, before_script]
  script:
    - !reference [.infraestructure_init, script]
    - !reference [.infraestructure_inventory, script]
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: always

.production-service-deploy:
  extends: .production
  before_script:
    - !reference [.setup, before_script]
  script:
    - !reference [.infraestructure_init, script]
    - !reference [.service_deploy, script]
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: manual