stages:
  - test

include:
  - local: '/core/pipeline/include/setup.gitlab-ci.yml'
  - local: '/core/pipeline/include/base.gitlab-ci.yml'
  - local: '/core/pipeline/include/infraestructure.gitlab-ci.yml'
  - local: '/core/pipeline/include/service.gitlab-ci.yml'

.test:
  variables:
    INVENTORY_FILE: '$CI_PROJECT_DIR/inventory_$CI_ENVIRONMENT_NAME.txt'
    OUTPUTS_FILE: '$CI_PROJECT_DIR/outputs_$CI_ENVIRONMENT_NAME.json'
  extends: .base
  stage: test
  environment:
    name: test

.test-inventory:
  extends: .test
  artifacts:
    untracked: false
    paths:
      - $CI_PROJECT_DIR/outputs_$CI_ENVIRONMENT_NAME.json
      - $CI_PROJECT_DIR/inventory_$CI_ENVIRONMENT_NAME.txt
    when: on_success
    expire_in: "30 days"
  before_script:
    - !reference [.setup, before_script]
  script:
    - !reference [.infraestructure_init, script]
    - !reference [.infraestructure_inventory, script]
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: always

.test-deploy:
  extends: .test
  before_script:
    - !reference [.setup, before_script]
  script:
    - !reference [.infraestructure_init, script]
    - !reference [.infraestructure_delete, script]
    - !reference [.infraestructure_create, script]
    - !reference [.service_deploy, script]
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: manual
  allow_failure: true

.test-destroy:
  extends: .test
  before_script:
    - !reference [.setup, before_script]
  script:
    - !reference [.infraestructure_init, script]
    - !reference [.infraestructure_delete, script]
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: manual
  allow_failure: true