stages:
  - test

include:
  - local: '/core/pipeline/include/setup.gitlab-ci.yml'
  - local: '/core/pipeline/include/base.gitlab-ci.yml'
  - local: '/core/pipeline/include/infraestructure.gitlab-ci.yml'
  - local: '/core/pipeline/include/service.gitlab-ci.yml'

.test:
  variables:
    INVENTORY_FILE: '$CI_PROJECT_DIR/inventory_test.txt'
  extends: .base
  stage: test
  environment:
    name: test

.test-deploy:
  extends: .test
  before_script:
    - !reference [.setup, before_script]
  script:
    - !reference [.infraestructure_init, script]
    - !reference [.infraestructure_delete, script]
    - !reference [.infraestructure_create, script]
    - !reference [.service_deploy, script]
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: manual
  allow_failure: true
  artifacts:
    when: on_success
    expire_in: never
    paths:
      - $INVENTORY_FILE