---
- name: Create VM using data from pipeline environment
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Plan VM deploy using terraform
      ansible.builtin.shell: |
        terraform -chdir=$CI_PROJECT_DIR/terraform apply -var-file="$CI_PROJECT_DIR/terraform/environments/test.tfvars" -auto-approve

    - name: Create Ansible inventory file
      ansible.builtin.shell: |
        terraform -chdir=$CI_PROJECT_DIR/terraform output -json | jq -r '.ip_address.value' > $CI_PROJECT_DIR/inventory.txt