# Global variables
variables:
  TF_VAR_project_slug: $CI_PROJECT_NAME # This is default name for VMs

# Included files
include:
  - local: '/pipeline/include/env.gitlab-ci.yml'
  - local: '/pipeline/test.gitlab-ci.yml'

# List of stages for jobs, and their order of execution
stages:
  - test

# JOBS: 
test-deploy:               # This job deploy test environment
  stage: test
  extends: .test-deploy
