# Global variables
variables:
  TF_VAR_project_slug: $CI_PROJECT_NAME # This is default name for VMs

# Included files
include:
  - local: '/core/pipeline/include/env.gitlab-ci.yml'
  - local: '/core/pipeline/test.gitlab-ci.yml'
  - local: '/core/pipeline/production.gitlab-ci.yml'

# List of stages for jobs, and their order of execution
stages:
  - test
  - production

# JOBS: 
test-deploy:               # This job deploy test environment
  stage: test
  extends: .test-deploy

production-deploy:         # This job deploy production environment
  stage: production
  extends: .production-deploy

production-redeploy:       # This job redeploy production environment
  stage: production
  extends: .production-redeploy

production-safe-redeploy:  # This job redeploy production environment with archive
  stage: production
  extends: .production-safe-redeploy