# Global variables
variables:
  TF_VAR_project_slug: $CI_PROJECT_NAME # This is default name for VMs

# Included files
include:
  - local: '/core/pipeline/include/env.gitlab-ci.yml'
  - local: '/core/pipeline/test.gitlab-ci.yml'
  - local: '/core/pipeline/staging.gitlab-ci.yml'
  - local: '/core/pipeline/production.gitlab-ci.yml'

# List of stages for jobs, and their order of execution
stages:
  - inventory
  - test
  - pre-staging
  - staging
  - production

# JOBS:

# Test environmnet jobs
Testing inventory:     # This job refresh inventory
  stage: inventory
  extends: .test-inventory

Testing deploy:               # This job deploy test environment
  stage: test
  extends: .test-deploy

Testing destroy:              # This job destroy test environment
  stage: test
  extends: .test-destroy

# Staging environment jobs
Staging inventory:     # This job refresh inventory
  stage: inventory
  extends: .staging-inventory

Staging testing deploy:
  stage: staging
  extends: .staging-empty-deploy

Staging create via clone:         # This job deploy staging environment
  stage: staging
  extends: .staging-create-via-clone

Staging service deploy:
  stage: staging
  extends: .staging-service-deploy

Staging destroy:              # This job destroy staging environment
  stage: staging
  extends: .staging-destroy

# Production environment jobs
Production inventory:     # This job refresh inventory
  stage: inventory
  extends: .production-inventory

Production deploy:         # This job deploy production environment
  stage: production
  extends: .production-deploy

Production redeploy:       # This job redeploy production environment
  stage: production
  extends: .production-redeploy

Production safe redeploy:  # This job redeploy production environment with archive
  stage: production
  extends: .production-safe-redeploy

Production service deploy:
  stage: production
  extends: .production-service-deploy