# Global variables
variables:
  TF_VAR_project_slug: $CI_PROJECT_NAME # This is default name for VMs

# Included files
include:
  - local: '/core/pipeline/include/env.gitlab-ci.yml'
  - local: '/core/pipeline/test.gitlab-ci.yml'
  - local: '/core/pipeline/staging.gitlab-ci.yml'
  - local: '/core/pipeline/production.gitlab-ci.yml'

# List of stages for jobs, and their order of execution
stages:
  - inventory
  - test
  - pre-staging
  - staging
  - production

# JOBS:

# Test environmnet jobs
test-inventory:     # This job refresh inventory
  stage: inventory
  extends: .test-inventory

test-deploy:               # This job deploy test environment
  stage: test
  extends: .test-deploy

# Staging environment jobs
staging-inventory:     # This job refresh inventory
  stage: inventory
  extends: .staging-inventory

staging-empty-deploy:
  stage: staging
  extends: .staging-empty-deploy

staging-create-via-clone:         # This job deploy staging environment
  stage: staging
  extends: .staging-create-via-clone

staging-service-deploy:
  stage: staging
  extends: .staging-service-deploy

# Production environment jobs
production-inventory:     # This job refresh inventory
  stage: inventory
  extends: .production-inventory

production-deploy:         # This job deploy production environment
  stage: production
  extends: .production-deploy

production-redeploy:       # This job redeploy production environment
  stage: production
  extends: .production-redeploy

production-safe-redeploy:  # This job redeploy production environment with archive
  stage: production
  extends: .production-safe-redeploy

production-service-deploy:
  stage: production
  extends: .production-service-deploy