stages:
  - test

include:
  - local: '/pipeline/include/setup.gitlab-ci.yml'
  - local: '/pipeline/include/base.gitlab-ci.yml'
  - local: '/pipeline/include/infraestructure.gitlab-ci.yml'
  - local: '/pipeline/include/service.gitlab-ci.yml'

.test:
  extends: .base
  stage: test
  environment:
    name: test

.test-deploy:
  extends: .test
  before_script:
    - !reference [.setup, before_script]
  script:
    - !reference [.infraestructure_init, script]
    - !reference [.infraestructure_delete, script]
    - !reference [.infraestructure_create, script]
    - !reference [.service, script]
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'