.infraestructure_init:
  script:
    - ansible-playbook $CI_PROJECT_DIR/core/pipeline/playbook/infraestructure/init.yml

.infraestructure_create:
  script:
    - ansible-playbook $CI_PROJECT_DIR/core/pipeline/playbook/infraestructure/create.yml

.infraestructure_delete:
  script:
    - ansible-playbook $CI_PROJECT_DIR/core/pipeline/playbook/infraestructure/delete.yml

.infraestructure_archive:
  script:
    - ansible-playbook $CI_PROJECT_DIR/core/pipeline/playbook/infraestructure/archive.yml

.infraestructure_clear_state:
  script:
    - ansible-playbook $CI_PROJECT_DIR/core/pipeline/playbook/infraestructure/clear_state.yml