variables:
  CUSTOM_INSTALL_LOCAL: '$CI_PROJECT_DIR/deploy/service_install_local.yml'
  CUSTOM_INSTALL: '$CI_PROJECT_DIR/deploy/service_install.yml'

.service_deploy:
  script:
    - 'ansible-playbook -i $INVENTORY_FILE $CI_PROJECT_DIR/core/pipeline/playbook/service/ping.yml'
    - 'if [ -f $CUSTOM_INSTALL_LOCAL ]; then ansible-playbook $CUSTOM_INSTALL_LOCAL; fi;'
    - 'if [ -f $CUSTOM_INSTALL ]; then ansible-playbook -i $INVENTORY_FILE $CUSTOM_INSTALL; fi;'
