# This is a sample playbook to run a command in the runner
# The playbook is written in YAML format
# This playbook is executed on the runner before the infraestructure creation
- name: Testing before create playbook
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Run a command
      shell: |
        echo "This command is executed before the infraestructure creation"
        echo "This command is executed on the Gitlab CI Runner"