# This is a sample playbook to run nginx server in docker container
# The playbook is written in YAML format
# This playbook is executed on the created infrastructure vm via ssh
# Install application and start services
- name: Install Docker
  ansible.builtin.import_playbook: lib/docker.service_install.yml

- name: Copy data folder to remote host
  ansible.builtin.import_playbook: lib/datacopy.service_install.yml
  vars:
    src: "{{ lookup('env', 'CI_PROJECT_DIR') }}/deploy/lib/example_data/"
    dst: "/home/tns"

- name: Testing install playbook
  hosts: all
  remote_user: tns      # use the user tns to connect to the host
  gather_facts: false
  tasks:
    - name: Run containers in docker
      ansible.builtin.shell: |
        docker compose -f example.docker-compose.yml up -d
        docker compose -f example.docker-compose.yml ps
      args:
        chdir: /home/tns/compose
